baseURL: 'https://mang3.net/'
languageCode: en-us
paginate: 5
title: mang3's blog
enableEmoji: true
theme: PaperMod
menu:
  main:
    - name: main
      url: /
      weight: -110
    - identifier: search 
      name: search 
      url: /search/
      weight: -100
params:
    homeInfoParams:
        Title: welcome to mang3's blog
        Content: this is my blog. it contains opinions, thoughts and ideas.
outputs:
    home:
        - HTML
        - RSS
        - JSON
